#! /usr/bin/env python3

import subprocess
import shutil
import os

SMALL_JSON = 'data/small-message.json'
BIG_JSON = 'data/big-message.json'
RESULTS_FILE = 'results.csv'

################################################################################
# Begin test procedure
################################################################################
# Clean-up any old garbage
try:
    os.remove(RESULTS_FILE)
except FileNotFoundError:
    pass

with open(RESULTS_FILE, 'w') as fout:
    subprocess.run(['tests/py-stdlib-json.py', SMALL_JSON, BIG_JSON], stdout=fout)
